site_name: Auto-Rei

repo_url: https://github.com/mdsreq-fga-unb/2024.2-T03-AutoReiTintas

nav:
  - Início: index.md
  - Visão do Produto e Projeto: 
    - Visão do Produto:
      - Cenário atual do cliente e do negócio: sections/product_vision/1_scenario.md
      - Solução proposta: sections/product_vision/2_solution.md
      - Estratégias de Engenharia de Software: sections/product_vision/3_strategy.md 
    - Visão do Projeto:
      - Engenharia de Requisitos: sections/product_vision/4_requirements_engineering.md
      - Interação entre equipe e cliente: sections/product_vision/6_interaction.md
      - Cronograma: sections/product_vision/5_timeline.md
  - Backlog:
    - Requisitos de Software: sections/product_vision/7_requirements.md
    - DoR e DoD: sections/product_vision/8_dorAndDod.md
    - Backlog: sections/product_vision/9_backlog.md
  - Sprints:
    - Sprint 1: sections/sprints/sprint1.md
    - Sprint 2: sections/sprints/sprint2.md
  - Estudos de Caso:
    - Estudo de Caso TechFix: sections/study_cases/study_case_PBB.md
    - Estudo de Caso EduConnect: sections/study_cases/study_case_USM.md
    - Estudo de Caso ConnectCare: sections/study_cases/study_case_UC.md
    - Especificações dos Casos de uso:
      - Cadastrar perfil do Paciente: sections/study_cases/especificacoes/cadastrar_perfil_paciente.md
      - Agendar Consulta: sections/study_cases/especificacoes/agendar_consulta.md
      - Cadastrar Campanha comunitária: sections/study_cases/especificacoes/cadastrar_campanha_comunitaria.md
      - Cadastrar Perfil do Profissional: sections/study_cases/especificacoes/cadastrar_perfil_profissional.md
      - Visualizar Histórico de Consulta: sections/study_cases/especificacoes/visualizar_historico_consulta.md
  - Apresentações e Entregas: 
    - Entrega Unidade 1: sections/presentations/presentation_1.md
    - Entrega Unidade 2: sections/presentations/presentation_2.md
    - Entrega Unidade 3: sections/presentations/presentation_3.md
    - Entrega Unidade 4: sections/presentations/presentation_4.md
  - Lições Aprendidas: sections/presentations/learned_lessons.md
  - Reuniões:
    - ATAS:
      - ATA 01-11: sections/atas/ata01-11.md
      - ATA 12-11: sections/atas/ata12-11.md
      - ATA 14-11: sections/atas/ata14-11.md
      - ATA 03-12: sections/atas/ata03-12.md
      - ATA 12-12: sections/atas/ata12-12.md
      - ATA 27-01: sections/atas/ata27-01.md
  - Como contribuir:
    - Ambiente de desenvolvimento: how_to_contribute/environment.md
    - Arquitetura de Software: sections/architecture/arquitetura.md
    - Política de Branchs: sections/branch_policy/politica_branch.md

theme:
  name: material
  #font:
  #  text: Fira Sans
  language: pt-BR
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: custom
      accent: custom

  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - content.code.copy
    - toc.integrate
    - content.tabs.link
    - header.autohide
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.keys
  - footnotes
  - admonition
  - markdown.extensions.attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

plugins:
  - search

fonts:
  icon: material/format-font
  preferences:
    - text: Default
    - text: Roboto
      code: Roboto Mono
    - text: OpenDyslexic
      code: OpenDyslexicMono
      src: https://fonts.cdnfonts.com/css/opendyslexic

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
